version: '3'

services:
  db:
    container_name: postgresql-studio
    image: postgres:11.2-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studio
    restart: always
    shm_size: '256mb'
    ports:
      - 5435:5432

  back:
    container_name: studio-back
    image: paice0510/api-studio
    env_file:
      - ./env_file.env
    restart: always
    depends_on:
      - db
    ports:
      - 3333:3333

  front:
    container_name: front-agendar
    image: paice0510/front-agendar
    ports:
      - 3000:80
